
services:
  #lab-api:
   # build:
    #  context: ../altair-lab-api-service
    #ports:
    #  - "8085:8085"
    #environment:
    #  DATABASE_URL: postgres://altair:altair@postgres:5432/altair
    #depends_on:
    #  - postgres

  postgres:
    image: postgres:16
    container_name: altair-postgres
    environment:
      POSTGRES_DB: altair
      POSTGRES_USER: altair
      POSTGRES_PASSWORD: altair
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/schema:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana:latest
    container_name: altair-grafana
    ports:
      - "4000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    container_name: keycloak
    command: start-dev --import-realm
    env_file:
      - .env
    environment:
      KC_DB: dev-file
    ports:
      - "8080:8080"
    volumes:
      # ✅ Import du realm
      - ./keycloak/realms:/opt/keycloak/data/import

      # ✅ THEMES (LA LIGNE QUI MANQUAIT)
      - ./keycloak/themes:/opt/keycloak/themes
